# Generated by Django 5.1.2 on 2024-10-21 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardapio',
            name='descricao',
            field=models.TextField(default='teste'),
            preserve_default=False,
        ),
    ]
